// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace PrimeiroApp
{
	public partial class Index : UIViewController
	{
		public Index (IntPtr handle) : base (handle)
		{
		}
	}
}
