// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace PrimeiroApp
{
	public partial class SorteioView : UIViewController
	{
		public SorteioView (IntPtr handle) : base (handle)
		{
        }

        partial void ButtonRandom_TouchUpInside(UIButton sender)
        {
            Random num = new Random();

            var num1 = num.Next(1,100);

            TextRandom.Text = "Numero sorteado: " + num1;
        }
    }
}
